### ISSUE TITLE
[mobile] problem in horizontal overflow of code

### ISSUE THREAD

**Issue by cnavarreteliz** [CodeLifeOrg/codelife#522]
![image](https://user-images.githubusercontent.com/5233593/46834227-347eca80-cd81-11e8-9e5e-75490c467b0b.png)

**Comment by alexandersimoes** [comment]
I believe this is fixed with the latest release could you try checking this again @cnavarreteliz 

Here's the direct URL: https://en.codelife.com/island/island-2/properties/slide2-5-8
