### ISSUE TITLE
Content editor link dialog box is semi-transparent

### ISSUE THREAD

**Issue by alexandersimoes** [CodeLifeOrg/codelife#524]
Weird CSS z-indexing bug on the add link pop up in the content text editor in the CMS. Take a look here:

<img width="955" alt="screen shot 2018-10-12 at 4 09 48 pm" src="https://user-images.githubusercontent.com/252276/46974018-df98c800-d090-11e8-98ab-92b34bb20292.png">
<img width="568" alt="screen shot 2018-10-12 at 4 17 01 pm" src="https://user-images.githubusercontent.com/252276/46974020-e0315e80-d090-11e8-8cef-a43dfd933080.png">

**Comment by alexandersimoes** [comment]
I still seem to be getting this issue when inserting a new link in the CMS. Can you confirm this on dev.codelife.com.

**Comment by perpetualgrimace** [comment]
still fixed in a90d2af
